
package Vista;

import Modelo.HistorialClinico;
import Modelo.Pacientes;
import controlador.HistorialClinicodb;
import controlador.Pacientedb;
import java.util.List;
import javax.swing.JOptionPane;
import utilidades.utilidades;



public class Registro_Pacientes extends javax.swing.JFrame {

    private utilidades utilidades;
    private Pacientedb controladorPacientedb;
    private Pacientes pacienteEditarEliminar;
    private HistorialClinicodb controladorHistorialClinicodb;
    private HistorialClinico historialSeleccionado;
 
   
    public Registro_Pacientes() {
         
         utilidades = new utilidades();
         controladorPacientedb = new Pacientedb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnTraer = new javax.swing.JButton();
        lbCedula = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        lbCorreo = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnBuscarCedula = new javax.swing.JButton();
        btnLimpiarFormulario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtTitulo1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbHCCedula = new javax.swing.JLabel();
        lbHCNombre = new javax.swing.JLabel();
        lbHCApellido = new javax.swing.JLabel();
        lbHCEdad = new javax.swing.JLabel();
        lbHCSexo = new javax.swing.JLabel();
        lbHCOcupacion = new javax.swing.JLabel();
        lbHCDireccion = new javax.swing.JLabel();
        lbHCCorreo = new javax.swing.JLabel();
        lbHCTelefono = new javax.swing.JLabel();
        txtHCedula = new javax.swing.JTextField();
        txtHNombre = new javax.swing.JTextField();
        txtHApellido = new javax.swing.JTextField();
        txtHEdad = new javax.swing.JTextField();
        txtHSexo = new javax.swing.JTextField();
        txtHOcupacion = new javax.swing.JTextField();
        txtHDireccion = new javax.swing.JTextField();
        TxtHCorreo = new javax.swing.JTextField();
        txtHTelefono = new javax.swing.JTextField();
        jbHGuardar = new javax.swing.JButton();
        jbHEditar = new javax.swing.JButton();
        jbHEliminar = new javax.swing.JButton();
        jbHcrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTitulo.setText("Registro de Pacientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuerpo Registro"));

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnTraer.setText("Traer");
        btnTraer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraerActionPerformed(evt);
            }
        });

        lbCedula.setText("Cedula");

        lbNombre.setText("Nombre");

        lbApellido.setText("Apellido");

        lbDireccion.setText("Direccion");

        lbCorreo.setText("Correo");

        lbTelefono.setText("Telefono");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnBuscarCedula.setText("Buscar");
        btnBuscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCedulaActionPerformed(evt);
            }
        });

        btnLimpiarFormulario.setText("Limpiar Formulario");
        btnLimpiarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarFormularioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombre)
                            .addComponent(lbApellido)
                            .addComponent(lbDireccion)
                            .addComponent(lbCorreo)
                            .addComponent(lbTelefono))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCedula)
                                .addComponent(txtApellido)
                                .addComponent(txtDireccion)
                                .addComponent(txtCorreo)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCedula))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnguardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnTraer)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarFormulario)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCedula)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarCedula)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnTraer)
                    .addComponent(btnLimpiarFormulario))
                .addContainerGap(431, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro de pacientes", jPanel2);

        txtTitulo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTitulo1.setText("Registro de Historial Clinico");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Curpo HistorialClinico"));

        lbHCCedula.setText("Cedula");

        lbHCNombre.setText("Nombre");

        lbHCApellido.setText("Apellido");

        lbHCEdad.setText("Edad");

        lbHCSexo.setText("Sexo");

        lbHCOcupacion.setText("Ocupacion");

        lbHCDireccion.setText("Direccion");

        lbHCCorreo.setText("Correo");

        lbHCTelefono.setText("Telefono");

        jbHGuardar.setText("Guardar");
        jbHGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHGuardarActionPerformed(evt);
            }
        });

        jbHEditar.setText("Editar");
        jbHEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHEditarActionPerformed(evt);
            }
        });

        jbHEliminar.setText("Eliminar");
        jbHEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHEliminarActionPerformed(evt);
            }
        });

        jbHcrear.setText("Crear");
        jbHcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHcrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHCCedula)
                            .addComponent(lbHCNombre)
                            .addComponent(lbHCApellido)
                            .addComponent(lbHCEdad)
                            .addComponent(lbHCSexo)
                            .addComponent(lbHCOcupacion)
                            .addComponent(lbHCDireccion)
                            .addComponent(lbHCCorreo)
                            .addComponent(lbHCTelefono))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jbHcrear)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jbHGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jbHEditar))
                    .addComponent(txtHCedula)
                    .addComponent(txtHNombre)
                    .addComponent(txtHApellido)
                    .addComponent(txtHEdad)
                    .addComponent(txtHSexo)
                    .addComponent(txtHOcupacion)
                    .addComponent(txtHDireccion)
                    .addComponent(TxtHCorreo)
                    .addComponent(txtHTelefono))
                .addGap(48, 48, 48)
                .addComponent(jbHEliminar)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHCCedula)
                    .addComponent(txtHCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHCNombre)
                    .addComponent(txtHNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHCApellido)
                    .addComponent(txtHApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHCEdad)
                    .addComponent(txtHEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHCSexo)
                    .addComponent(txtHSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHCOcupacion)
                    .addComponent(txtHOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHCDireccion)
                    .addComponent(txtHDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHCCorreo)
                    .addComponent(TxtHCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHCTelefono)
                    .addComponent(txtHTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbHGuardar)
                    .addComponent(jbHEditar)
                    .addComponent(jbHEliminar)
                    .addComponent(jbHcrear))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 309, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro Historial Clinico", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jTabbedPane1)
                .addGap(719, 719, 719))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       if(controladorPacientedb.getPacientesCedula(txtCedula.getText())!=null){
       JOptionPane.showMessageDialog(rootPane,"La persona con ese numeronde cedula ya se encuntra registrada","ERROR",JOptionPane.ERROR_MESSAGE);
       }else{
       Pacientes pacienteGuardar = guardarEditar();
        if(pacienteGuardar!=null){
            if(controladorPacientedb.registarPaciente(pacienteGuardar)){
        JOptionPane.showMessageDialog(rootPane,"Paciente guardado exitosamente");
        limpiarCamposPacientes();
        }else{
        JOptionPane.showMessageDialog(rootPane,"No se puede guardar el paciente","ERROR",JOptionPane.ERROR_MESSAGE);
        }
       
       }
        
        
            
            
        }
        
       
    }//GEN-LAST:event_btnguardarActionPerformed

    public Pacientes guardarEditar(){
    
    if(txtCedula.getText().isEmpty()){
           JOptionPane.showMessageDialog(rootPane,"El campo cedula no tiene datos","ERROR",JOptionPane.ERROR_MESSAGE);
           txtCedula.requestFocus();
           return null;
        }
        if(!utilidades.validadorDeCedula(txtCedula.getText())){
        JOptionPane.showMessageDialog(rootPane,"Lacedula ingresada no es valida","ERROR",JOptionPane.ERROR_MESSAGE);
        }
         if(txtNombre.getText().isEmpty()){
           JOptionPane.showMessageDialog(rootPane,"El campo nombre no tiene datos","ERROR",JOptionPane.ERROR_MESSAGE);
           txtNombre.requestFocus();
           return null;
        }
          if(txtApellido.getText().isEmpty()){
           JOptionPane.showMessageDialog(rootPane,"El campo apellido no tiene datos","ERROR",JOptionPane.ERROR_MESSAGE);
           txtApellido.requestFocus();
           return null;
        }
           if(txtDireccion.getText().isEmpty()){
           JOptionPane.showMessageDialog(rootPane,"El campo direccion no tiene datos","ERROR",JOptionPane.ERROR_MESSAGE);
           txtDireccion.requestFocus();
           return null;
        }
            if(txtCorreo.getText().isEmpty()){
           JOptionPane.showMessageDialog(rootPane,"El campo correo no tiene datos","ERROR",JOptionPane.ERROR_MESSAGE);
           txtCorreo.requestFocus();
           return null;
        }
            if(!utilidades.validarCorreo(txtCorreo.getText())){
            JOptionPane.showMessageDialog(rootPane,"Los datos ingresados en correo no son validos","ERROR",JOptionPane.ERROR_MESSAGE);
            }
             if(txtTelefono.getText().isEmpty()){
           JOptionPane.showMessageDialog(rootPane,"El campo telefono no tiene datos","ERROR",JOptionPane.ERROR_MESSAGE);
           txtTelefono.requestFocus();
           return null;
        }
             if(!utilidades.validarNumeros(txtTelefono.getText())){
             JOptionPane.showMessageDialog(rootPane,"Los datos ingresados en telefono no son validos","ERROR",JOptionPane.ERROR_MESSAGE);
             }
        Pacientes pacientes = new Pacientes ();
        pacientes.setCedula(txtCedula.getText());
        pacientes.setNombre(txtNombre.getText());
        pacientes.setApellido(txtApellido.getText());
        pacientes.setDireccion(txtDireccion.getText());
        pacientes.setCorreo(txtCorreo.getText());
        pacientes.setTelefono(txtTelefono.getText());
        return pacientes;
        
        
    
    }
    
    
    
    
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       if(pacienteEditarEliminar ==null){
           JOptionPane.showMessageDialog(rootPane,"No hay una persona seleccionada para editar","ERROR",JOptionPane.ERROR_MESSAGE);
       return;
       
       }
       
       Pacientes pacienteEditarlocal = guardarEditar();
       if(pacienteEditarlocal!=null){
           pacienteEditarlocal.setIdpacientes(pacienteEditarEliminar.getIdpacientes());
        controladorPacientedb.actualizar(pacienteEditarlocal);
         JOptionPane.showMessageDialog(rootPane,"Paciente editado con exito ");
        limpiarCamposPacientes();
        pacienteEditarEliminar = null;
       }else{
        JOptionPane.showMessageDialog(rootPane,"No se puedo editar el paciente","ERROR",JOptionPane.ERROR_MESSAGE);
        }
       
        

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnTraerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraerActionPerformed
        // TODO add your handling code here:
        List<Pacientes> obtenerPacientes = controladorPacientedb.obtenerPacientes();
        pacienteEditarEliminar = obtenerPacientes.get(obtenerPacientes.size()-1);
        txtCedula.setText(pacienteEditarEliminar.getCedula());
        txtNombre.setText(pacienteEditarEliminar.getNombre());
        txtApellido.setText(pacienteEditarEliminar.getApellido());
        txtDireccion.setText(pacienteEditarEliminar.getCorreo());
        txtTelefono.setText(pacienteEditarEliminar.getTelefono());
    }//GEN-LAST:event_btnTraerActionPerformed

    private void btnBuscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCedulaActionPerformed
        Pacientes paciente = controladorPacientedb.getPacientesCedula(txtCedula.getText());
        if(paciente!=null){
        txtNombre.setText(paciente.getNombre());
        txtApellido.setText(paciente.getApellido());
        txtDireccion.setText(paciente.getDireccion());
        txtCorreo.setText(paciente.getCorreo());
        txtTelefono.setText(paciente.getTelefono());
        pacienteEditarEliminar = paciente;
         }else{
        JOptionPane.showMessageDialog(rootPane,"Paciente no encontrado en el sistema","ERROR",JOptionPane.ERROR_MESSAGE);
        txtCedula.setText("");
        txtCedula.requestFocus();
        }
       
        
        
        
    }//GEN-LAST:event_btnBuscarCedulaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      if(pacienteEditarEliminar!=null){
          if(controladorPacientedb.eliminar(pacienteEditarEliminar)){
             JOptionPane.showMessageDialog(rootPane,"Paciente eliminado con exito del sistema "); 
             limpiarCamposPacientes();
          }else{
           JOptionPane.showMessageDialog(rootPane,"No se puede eliminar la persona selecionada","ERROR",JOptionPane.ERROR_MESSAGE);
          }
       
      }else{
      JOptionPane.showMessageDialog(rootPane,"No hay paciente seleccionado para eliminar","ERROR",JOptionPane.ERROR_MESSAGE);
      }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarFormularioActionPerformed
        limpiarCamposPacientes();
    }//GEN-LAST:event_btnLimpiarFormularioActionPerformed

    private void jbHcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHcrearActionPerformed
        HistorialClinico c = new HistorialClinico();
        c.setCedula(txtHCedula.getText());
        c.setNombre(txtHNombre.getText());
        c.setApellido(txtHApellido.getText());
        c.setEdad(WIDTH);
        c.setSexo(txtHSexo.getText());
        c.setOcupacion(txtHOcupacion.getText());
        c.setDireccion(txtHDireccion.getText());
        c.setCorreo(TxtHCorreo.getText());
        c.setTelefono(txtHTelefono.getText());
        controladorHistorialClinicodb.registarHistorialClinico(c);
        
    }//GEN-LAST:event_jbHcrearActionPerformed

    private void jbHEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHEliminarActionPerformed
         if (historialSeleccionado != null) {
            if (controladorHistorialClinicodb.eliminar(historialSeleccionado)) {
                JOptionPane.showMessageDialog(rootPane, "Historial Clinico eliminado con éxito del sitema.");
                limpiarHistorial();
                historialSeleccionado = null;
               
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar el historial seleccionado.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay historial seleccionado para eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbHEliminarActionPerformed

    private void jbHGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHGuardarActionPerformed
         HistorialClinico c = new HistorialClinico();
        c.setCedula(txtHCedula.getText());
        c.setNombre(txtHNombre.getText());
        c.setApellido(txtHApellido.getText());
        c.setEdad(WIDTH);
        c.setSexo(txtHSexo.getText());
        c.setOcupacion(txtHOcupacion.getText());
        c.setDireccion(txtHDireccion.getText());
        c.setCorreo(TxtHCorreo.getText());
        c.setTelefono(txtHTelefono.getText());
        controladorHistorialClinicodb.registarHistorialClinico(c);
         if (controladorHistorialClinicodb.eliminar(historialSeleccionado)) {
                JOptionPane.showMessageDialog(rootPane, "Historial Clinico guardadoo con éxito del sitema.");
                limpiarHistorial();
                historialSeleccionado = null;
               
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar el historial seleccionado.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jbHGuardarActionPerformed

    private void jbHEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHEditarActionPerformed
         if (historialSeleccionado == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay un historial seleccionado para editar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (historialSeleccionado != null) {
            
            if (controladorHistorialClinicodb.actualizar(historialSeleccionado)) {
                JOptionPane.showMessageDialog(rootPane, "Producto editado con exito del sitema.");
                limpiarHistorial();
                historialSeleccionado = null;
               
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede editar la Producto", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbHEditarActionPerformed

    public void limpiarCamposPacientes(){
    
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtDireccion.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtCedula.requestFocus();
    
    
    }
    
    public void limpiarHistorial(){
     txtHCedula.setText("");
        txtHNombre.setText("");
        txtHApellido.setText("");
        setEdad(WIDTH);
        txtHSexo.setText("");
        txtHOcupacion.setText("");
        txtHDireccion.setText("");
        TxtHCorreo.setText("");
        txtHTelefono.setText("");
    
    
    
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Pacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtHCorreo;
    private javax.swing.JButton btnBuscarCedula;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiarFormulario;
    private javax.swing.JButton btnTraer;
    private javax.swing.JButton btnguardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbHEditar;
    private javax.swing.JButton jbHEliminar;
    private javax.swing.JButton jbHGuardar;
    private javax.swing.JButton jbHcrear;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbCedula;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbHCApellido;
    private javax.swing.JLabel lbHCCedula;
    private javax.swing.JLabel lbHCCorreo;
    private javax.swing.JLabel lbHCDireccion;
    private javax.swing.JLabel lbHCEdad;
    private javax.swing.JLabel lbHCNombre;
    private javax.swing.JLabel lbHCOcupacion;
    private javax.swing.JLabel lbHCSexo;
    private javax.swing.JLabel lbHCTelefono;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtHApellido;
    private javax.swing.JTextField txtHCedula;
    private javax.swing.JTextField txtHDireccion;
    private javax.swing.JTextField txtHEdad;
    private javax.swing.JTextField txtHNombre;
    private javax.swing.JTextField txtHOcupacion;
    private javax.swing.JTextField txtHSexo;
    private javax.swing.JTextField txtHTelefono;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtTitulo1;
    // End of variables declaration//GEN-END:variables
}
